# Generated by Django 2.2.1 on 2019-05-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('uri', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Sta', 'Started'), ('Tpr', 'Getting the text in progress'), ('Ipr', 'Getting images in progress'), ('Suc', 'Success'), ('Fai', 'Failed')], default='Sta', max_length=3)),
                ('images_count', models.PositiveIntegerField(default=0)),
                ('extra_context', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='WebsiteText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='website_process.Website')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='WebsiteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_file', models.CharField(max_length=255)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website_process.Website')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
